---

version: '3'
services:

  tac-mh-postgres:
    image: postgres:9.5
    container_name: 'api-book-postgres'
    hostname: 'api-mh-postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookApi
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'
      - './postgres/sql-files:/sql-files'
